# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_analytics.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x61ta_analytics.proto\"\x07\n\x05\x45mpty\"f\n\x10logdataanalytics\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0f\n\x07\x65xtra_1\x18\x04 \x01(\t\x12\x0f\n\x07\x65xtra_2\x18\x05 \x01(\t2=\n\x11SimulationService\x12(\n\x0bReportCycle\x12\x11.logdataanalytics\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=24
  _globals['_EMPTY']._serialized_end=31
  _globals['_LOGDATAANALYTICS']._serialized_start=33
  _globals['_LOGDATAANALYTICS']._serialized_end=135
  _globals['_SIMULATIONSERVICE']._serialized_start=137
  _globals['_SIMULATIONSERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
